### ISSUE TITLE
problem with calssifier

### ISSUE THREAD

**Issue by shacharEtt** [plai-group/ccfs-python#1]
Hello, I have a problem with running the classifier on other datasets.
The example works perfectly (you are  just missing src. in the imports in plot_surface.py).
The issue is when I try it on other datasets (only numerical, binary classes)- there are all sorts of errors coming up regarding number of features and number of axis in different parts of the code.
To check I even used the spiral dataset with 1 added feature and did not get a result (when only adding samples it worked).

Can you help me? Is there a more general version of the code or maybe you can think of a way I'm implementing the code wrong?

Thank you,
Shachar.

**Comment by tonyjo** [comment]
Added a new example set for classification with more than 1 feature.
